routes/web.php
<?php

use Illuminate\Contracts\Console\Kernel;

// Frontoffice -> Routes

// Index
Route::get('/', 'HomeIndexController@index')->name('index');

//Sobre
Route::get('/sobre', 'PageController@sobre')->name('sobre');

//Contactos
Route::get('/contactos', 'ContactController@contact')->name('contact');
Route::post('/contactos', 'ContactController@contactPost')->name('contactPost');

//Divulgações - Listagem
Route::get('/divulgacoes/{service}', 'PostListController@index')->name('divulgacoes');

//Divulgações - Detalhe
Route::get('/divulgacoes/{service}/divulgacao/{post}', 'PostDetailController@index')->name('divulgacao');

Route::get('/divulgacoes/svgImage/{post}', 'SvgController@getSvg')->name('divulgacoes.svg');
Route::get('/divulgacoes/svgThumb/{post}', 'SvgController@getSvgThumb')->name('divulgacoes.svgThumb');

// Backoffice -> Routes

// Auth
Route::get('/backoffice/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::get('/backoffice/autologin/{number}', 'Auth\LoginController@autoLogin')->name('autologin');
Route::get('/backoffice/logout', 'Auth\LoginController@logout')->name('logout');
Route::post('/backoffice/login', 'Auth\LoginController@postLogin');


Route::group(['prefix' => 'backoffice', 'middleware' => ['auth','PreventBackButton']], function () {

    //Home
    Route::get('/', 'HomeController@index')->name('home');

    //Notes
    Route::resource('/notes', 'NoteController')->only([
        'store', 'update', 'destroy'
    ]);

    //Statistics
    Route::resource('/statistics', 'StatisticsController');

    //Users
    Route::get('/users//restore/{user}', 'UserController@restore')->name('users.restore');
    Route::get('/users/restore', 'UserController@show_trashed')->name('users.trashed');
    Route::resource('/users', 'UserController');

    //Services: EDIT info
    Route::resource('/services', 'ServicesController');

    //FAQs
    Route::get('/faqs', 'FaqsController@show')->name('faqs');

    //Options
    Route::get('/options/reset', 'OptionsController@show_reset')->name('resetpage');


    //Reset à base de dados : migrate:refresh
    Route::get('/options/resetdata', function () {
        $exitCode = Artisan::call('migrate:refresh');
        return redirect()->route('options', Auth::user())->with('success', 'Valores de origem repostos com sucesso');
    })->name('resetdatabase');

/*     //backup database. php artisan backup:mysql-dump
    Route::get('/options/backup/makebackup', function () {
        $exitCode = Artisan::call('backup:mysql-dump');
        return redirect()->route('options', Auth::user())->with('success', 'Cópia de segurança da base de dados efectuada com sucesso');
    })->name('makebackup'); */





    Route::get('/options/backup', 'OptionsController@show_backup')->name('backupdatabase');
    Route::get('/options/{user}', 'OptionsController@index')->name('options');


    //Drafts
    Route::resource('/drafts', 'DraftController');

    // Newsletter
    Route::get('/newsletters', 'NewsletterController@index')->name('newsletters.index');
    Route::get('/newsletters/create', 'NewsletterController@create')->name('newsletters.create');
    Route::post('/newsletters/preview', 'NewsletterController@preview')->name('newsletters.preview');
    Route::post('/newsletters/store', 'NewsletterController@store')->name('newsletters.store');
    Route::delete('/newsletters/{newsletter}', 'NewsletterController@destroy')->name('newsletters.destroy');


    //Drafts
    Route::resource('/drafts', 'DraftController')->only(['index', 'show', 'edit', 'destroy']);

    //Events
    Route::resource('/events', 'EventController')->only([
        'index', 'show', 'edit', 'destroy'
    ]);

    //Posts
    Route::get('/posts/create/{tipo}','PostController@create')->name('posts.create');
    Route::resource('/posts', 'PostController')->except(['create']);

    //Tasks
    Route::resource('/tasks', 'TaskController')->only([
        'index', 'store', 'update', 'destroy'
    ]);

    //SubTasks
    Route::resource('/subtasks', 'SubTaskController')->only([
        'index', 'store', 'update', 'destroy'
    ]);
    Route::put('/updatesubtaskstatusdone/{id}',[
      'as' => 'subtasks.updateStatusDone',
      'uses' => 'SubTaskController@updateStatusDone'
    ]);
    Route::put('/updatesubtaskstatustodo/{id}',[
      'as' => 'subtasks.updateStatusTodo',
      'uses' => 'SubTaskController@updateStatusTodo'
    ]);

    //EventTypes
    Route::resource('/eventtypes', 'EventTypeController')->only([
        'index', 'store', 'update', 'destroy'
    ]);

    //TargetAudience
    Route::resource('/targetaudiences', 'TargetAudienceController')->only([
        'index', 'store', 'update', 'destroy'
    ]);
    Route::get('/getEmails', 'TargetAudienceController@getEmails');

    Route::put('/notifications/markAsRead/{id}', 'NotificationController@markAsRead');
});

app/EventType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class EventType extends Model
{
  use SoftDeletes;

  protected $fillable = ['name', 'icon', 'service_id'];
  protected $table = 'eventTypes';

  public function posts(){
      return $this->hasMany("App\Post","eventtype_id");
  }

  public function service(){
      return $this->belongsTo("App\Service","service_id");
  }
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Auth;
use App\Service;

class EventController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $menuPostType = 'Event';
        $menuPostStatus = '';
        if (Auth::user()->isAdmin()) {
            $services = Service::all();
            $posts = Post::where('type', 'Event')
                ->where ('status', 'Published')
                ->get();
            return view('backoffice.events.list', compact('posts', 'services', 'menuPostType', 'menuPostStatus'));
        } else {
            $service = Service::findOrFail(Auth::user()->service_id);
            $posts = $service->posts->where ('type', 'Event');
            return view('backoffice.events.list', compact('posts', 'menuPostType', 'menuPostStatus'));
        }
    }
}

resources/views/backoffice/events/list.blade.php
@extends('layout.masterbackoffice')

@section('styleLinks')
    <link href="{{asset('css/dataTables.bootstrap4.min.css')}}" rel="stylesheet">
@endsection

@section('title', 'Eventos')

@section('content')
    @include('backoffice.posts.partials.modal')

    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Eventos</h1>
        <a href="{{route('posts.create','Event')}}" class="btn btn-sm btn-primary shadow-sm"><i
                class="fas fa-plus text-white-50 mr-2"></i>Adicionar Evento</a>
    </div>

    <!-- Content Row -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Lista de Eventos</h6>
        </div>
        <div class="card-body">
            @if (count($posts))
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Título</th>
                            <th>Data de Publicação</th>
                            <th>Estado</th>
                            @if(Auth::user()->isAdmin())
                                <th>Gabinete</th>@endif
                            {{--<th>Destaque</th>--}}
                            <th style="width: 50px">Opções</th>
                        </tr>
                        </thead>

                        <tbody>
                        @foreach($posts as $post)
                            <tr>
                                <td>{{$post->title}}</td>
                                <td>{{date('d/m/Y', strtotime($post->created_at))}}</td>
                                <td>@switch($post->status)
                                        @case('Published')
                                        Publicado
                                        @break
                                        @case('Draft')
                                        Rascunho
                                        @break
                                        @case('Archived')
                                        Arquivado
                                        @break
                                        @default
                                        Publicado
                                    @endswitch
                                </td>
                                @if(Auth::user()->isAdmin())
                                    <td>{{$post->service->initial}}</td>@endif
                                {{--<td>{{$post->service->name}}</td>--}}
                                {{--                                <td>
                                                                    <form action="{{route('posts.destaque',$post)}}" method="post">
                                                                        @method('PATCH')
                                                                        @csrf
                                                                        <input type="checkbox" onclick="this.form.submit();">
                                                                        <!--@ if ($post->destaque) checked @ endif-->
                                                                    </form>
                                                                </td>--}}
                                <td nowrap>
                                    <a class="btn btn-sm btn-outline-primary" href="{{route('posts.show',$post->id)}}"
                                       title='Visualizar'><i class="fas fa-eye"></i></a>

                                    <a class="btn btn-sm btn-outline-warning" href="{{route('posts.edit',$post->id)}}"
                                       title='Editar'><i class="fas fa-pen"></i></a>

                                    <form method="POST" action="{{route('posts.destroy',$post->id)}}" role="form"
                                          class="d-inline-block form_post_id" title='Eliminar'>
                                        @csrf
                                        @method("DELETE")

                                        <button type="button" class="btn btn-sm btn-outline-danger" data-toggle="modal"
                                                data-target="#modalEliminar" data-title="{{$post->title}}"><i
                                                class="fas fa-trash-alt"></i></button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            @else
                <h6 style="text-align: center">Sem Eventos Disponíveis</h6>
            @endif
        </div>
    </div>
@endsection

@section("scripts")
    <script>
        $('#dataTable').dataTable({
            "order": [[1, 'desc']],
            'language': {'url': '//cdn.datatables.net/plug-ins/1.10.19/i18n/Portuguese.json'}
        });

        $(document).ready(function () {
            $('#modalEliminar').on('show.bs.modal', function (e) {
                $("#eliminarDivulgacao").click(function () {
                    $(e.relatedTarget).parent().submit();
                });
                $("#titulo").text($(e.relatedTarget).data("title"));
            });
        });
    </script>
@endsection