routes/web.php
<?php

use Illuminate\Contracts\Console\Kernel;

// Frontoffice -> Routes

// Index
Route::get('/', 'HomeIndexController@index')->name('index');

//Sobre
Route::get('/sobre', 'PageController@sobre')->name('sobre');

//Contactos
Route::get('/contactos', 'ContactController@contact')->name('contact');
Route::post('/contactos', 'ContactController@contactPost')->name('contactPost');

//Divulgações - Listagem
Route::get('/divulgacoes/{service}', 'PostListController@index')->name('divulgacoes');

//Divulgações - Detalhe
Route::get('/divulgacoes/{service}/divulgacao/{post}', 'PostDetailController@index')->name('divulgacao');

Route::get('/divulgacoes/svgImage/{post}', 'SvgController@getSvg')->name('divulgacoes.svg');
Route::get('/divulgacoes/svgThumb/{post}', 'SvgController@getSvgThumb')->name('divulgacoes.svgThumb');

// Backoffice -> Routes

// Auth
Route::get('/backoffice/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::get('/backoffice/autologin/{number}', 'Auth\LoginController@autoLogin')->name('autologin');
Route::get('/backoffice/logout', 'Auth\LoginController@logout')->name('logout');
Route::post('/backoffice/login', 'Auth\LoginController@postLogin');


Route::group(['prefix' => 'backoffice', 'middleware' => ['auth','PreventBackButton']], function () {

    //Home
    Route::get('/', 'HomeController@index')->name('home');

    //Notes
    Route::resource('/notes', 'NoteController')->only([
        'store', 'update', 'destroy'
    ]);

    //Statistics
    Route::resource('/statistics', 'StatisticsController');

    //Users
    Route::get('/users//restore/{user}', 'UserController@restore')->name('users.restore');
    Route::get('/users/restore', 'UserController@show_trashed')->name('users.trashed');
    Route::resource('/users', 'UserController');

    //Services: EDIT info
    Route::resource('/services', 'ServicesController');

    //FAQs
    Route::get('/faqs', 'FaqsController@show')->name('faqs');

    //Options
    Route::get('/options/reset', 'OptionsController@show_reset')->name('resetpage');


    //Reset à base de dados : migrate:refresh
    Route::get('/options/resetdata', function () {
        $exitCode = Artisan::call('migrate:refresh');
        return redirect()->route('options', Auth::user())->with('success', 'Valores de origem repostos com sucesso');
    })->name('resetdatabase');

/*     //backup database. php artisan backup:mysql-dump
    Route::get('/options/backup/makebackup', function () {
        $exitCode = Artisan::call('backup:mysql-dump');
        return redirect()->route('options', Auth::user())->with('success', 'Cópia de segurança da base de dados efectuada com sucesso');
    })->name('makebackup'); */





    Route::get('/options/backup', 'OptionsController@show_backup')->name('backupdatabase');
    Route::get('/options/{user}', 'OptionsController@index')->name('options');


    //Drafts
    Route::resource('/drafts', 'DraftController');

    // Newsletter
    Route::get('/newsletters', 'NewsletterController@index')->name('newsletters.index');
    Route::get('/newsletters/create', 'NewsletterController@create')->name('newsletters.create');
    Route::post('/newsletters/preview', 'NewsletterController@preview')->name('newsletters.preview');
    Route::post('/newsletters/store', 'NewsletterController@store')->name('newsletters.store');
    Route::delete('/newsletters/{newsletter}', 'NewsletterController@destroy')->name('newsletters.destroy');


    //Drafts
    Route::resource('/drafts', 'DraftController')->only(['index', 'show', 'edit', 'destroy']);

    //Events
    Route::resource('/events', 'EventController')->only([
        'index', 'show', 'edit', 'destroy'
    ]);

    //Posts
    Route::get('/posts/create/{tipo}','PostController@create')->name('posts.create');
    Route::resource('/posts', 'PostController')->except(['create']);

    //Tasks
    Route::resource('/tasks', 'TaskController')->only([
        'index', 'store', 'update', 'destroy'
    ]);

    //SubTasks
    Route::resource('/subtasks', 'SubTaskController')->only([
        'index', 'store', 'update', 'destroy'
    ]);
    Route::put('/updatesubtaskstatusdone/{id}',[
      'as' => 'subtasks.updateStatusDone',
      'uses' => 'SubTaskController@updateStatusDone'
    ]);
    Route::put('/updatesubtaskstatustodo/{id}',[
      'as' => 'subtasks.updateStatusTodo',
      'uses' => 'SubTaskController@updateStatusTodo'
    ]);

    //EventTypes
    Route::resource('/eventtypes', 'EventTypeController')->only([
        'index', 'store', 'update', 'destroy'
    ]);

    //TargetAudience
    Route::resource('/targetaudiences', 'TargetAudienceController')->only([
        'index', 'store', 'update', 'destroy'
    ]);
    Route::get('/getEmails', 'TargetAudienceController@getEmails');

    Route::put('/notifications/markAsRead/{id}', 'NotificationController@markAsRead');
});

app/User.php
<?php

namespace App;

use App\Service;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;


class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;

    protected $primaryKey = "user";
    public $incrementing = false;


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */

    //user name email photo role service_id
    protected $fillable = ['user', 'photo', 'role', 'service_id'];
    protected $table = 'users';

    public function posts(){
        return $this->hasMany("App\Post","user");
    }

    public function tasks(){
        return $this->hasMany("App\Task","user");
    }

    public function notes(){
        return $this->hasMany("App\Note","user");
    }

    public function service(){
        return $this->belongsTo("App\Service","service_id");
    }

    public function roleToStr()
    {
        switch ($this->role) {
            case 'Employer':
                return 'Funcionário';
            case 'Admin':
                return 'Administrador';
        }
    }


    public function serviceToStr()
    {
        if ($this->service_id == null){
            return 'Não atribuido';
        }else{
            $initial = SERVICE::where('id', $this->service_id)->first()->initial;
            return $initial;
        }
    }




    public function isAdmin()
    {
        return $this->role == 'Admin';
    }


}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\StoreUserRequest;
use App\Http\Requests\UpdateUserRequest;
use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\SoftDeletes;



class UserController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(User::class, 'user');
    }

    /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function index(Request $request)
    {


        if(Auth::User()->role!='Admin'){
            abort (401);
        }


        /* Utilizadores */
        if (count($request->all()) == 0) {
            $users = User::all();
        } else {
            $users = User::query();
            if ($request->filled('user')) {
                $users->where('user', 'like', '%' . $request->user . '%');
            }
            if ($request->filled('name')) {
                $users->where('name', 'like', '%' . $request->name . '%');
            }
            if ($request->filled('email')) {
                $users->where('email', 'like', '%' . $request->email . '%');
            }
            if ($request->filled('role')) {
                $users->where('role', $request->role);
            }
            if ($request->filled('service_id')) {
                $users->where('service_id', $request->service_id);
            }
            $users = $users->get();
        }


        return view('backoffice.users.list', compact('users'));
    }



    /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function create()
    {
        $user = new User;
        $services = DB::table('services')->get();
        return view('backoffice.users.add', compact('user','services'));
    }






    /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
    public function store(StoreUserRequest $request)
    {
        $fields = $request->validated();
        $user = new User;
        $user->fill($fields);


        if ($request->hasFile('photo')) {
            $photo = $request->file('photo');
            $profileImg = $user->user . '_' . time() . '.' . $photo->getClientOriginalExtension();
            Storage::disk('public')->putFileAs('users_photos/', $photo, $profileImg);
            $user->photo = $profileImg;
            $user->save();
        }

        // data em que foi criado
        $t=time();
        $user->create_at == date("Y-m-d",$t);

        $user->save();

        return redirect()->route('users.index')->with('success', 'Utilizador criado com sucesso ');
    }





        /***********************************************************************//*
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    * @param  \App\User  $user
    */
    public function show_trashed(User $user)
    {
        $users = User::onlyTrashed()->get();
        return view('backoffice.users.restore',compact("users"));
    }





    /***********************************************************************//*
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    * @param  \App\User  $user
    */
    public function restore($user)
    {
        if ($user!=null){
            User::withTrashed()->where("user",$user)->restore();
            return redirect()->route('users.trashed')->with('success', 'Utilizador recuperado com sucesso');
        }else{
            return redirect()->route('users.trashed')->with('errors', 'Utilizador não identificado');
        }
    }





    /**
    * Display the specified resource.
    *
    * @param  \App\User  $user
    * @return \Illuminate\Http\Response
    */
    public function show(User $user)
    {

        // POSTS do utilizaror
        $posts = DB::table('posts')
        ->select('*')
        ->where('user', $user->user)
        ->get();


        // NEWSLETTERS do utilizador
        $newsletters = DB::table('newsletters')
        ->select('*')
        ->where('user', $user->user)
        ->get();

        return view('backoffice.users.show', compact("user","posts",'newsletters'));


    }




    /**
    * Show the form for editing the specified resource.
    *
    * @param  \App\User  $user
    * @return \Illuminate\Http\Response
    */
    public function edit(User $user)
    {
        $services = DB::table('services')->get();

        return view('backoffice.users.edit', compact('user','services'));
    }






    /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  \App\User  $user
    * @return \Illuminate\Http\Response
    */
    public function update(UpdateUserRequest $request, User $user)
    {

        $fields = $request->validated();
        $user->fill($fields);


        if ($request->photo==null){
            $user->photo = "default_user.png";
        }

        if ($request->hasFile('photo')) {
            $photo = $request->file('photo');
            $profileImg = $user->user . '_' . time() . '.' . $photo->getClientOriginalExtension();
            if (!empty($user->photo)) {
                Storage::disk('public')->delete('users_photos/' . $user->photo);
            }
            Storage::disk('public')->putFileAs('users_photos/', $photo, $profileImg);
            $user->photo = $profileImg;
        }

        if($user->role=="Admin"){
            $user->service_id=null;
        }

        // data em que foi modificado
        $t=time();
        $user->updated_at == date("Y-m-d",$t);

        $user->save();


        if (Auth::user()->role=="Admin"){
            return redirect()->route('users.index')->with('success', 'Dados do utilizador modificados com sucesso');
        }else{
            return redirect()->route('options',Auth::user()->user)->with('success', 'Dados do utilizador modificados com sucesso');
        }
        

    }




    /*     public function send_reactivate_email(User $user)
    {
        $user->sendEmailVerificationNotification();
        return $this->edit($user);
    } */





    /**
    * Remove the specified resource from storage.
    *
    * @param  \App\User  $user
    * @return \Illuminate\Http\Response
    */
    public function destroy(User $user) //
    {

        //$user = User::findOrFail($request->modalUserid);
        $user->delete();
        return redirect()->route('users.index')->with('success', 'Utilizador eliminado com sucesso');
    }

}

resources/views/backoffice/users/list.blade.php
@extends('layout.masterbackoffice')


@section('title', 'Utilizadores')



@section('styleLinks')
<link href="{{asset('css/style_users.css')}}" rel="stylesheet">
<link href="{{asset('css/dataTables.bootstrap4.min.css')}}" rel="stylesheet">
@endsection


@section('content')
@include('backoffice.users.partials.modal') <!-- MODAL DE INFORMAÇÔES -->


<div class="d-sm-flex align-items-right justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800 text-right">Utilizadores</h1>

    @can("create",App\User::class)
    <div>
        <a href="{{route('users.trashed')}}" class="btn btn-sm btn-primary shadow-sm mr-2"><i class="fas fa-trash-restore text-white-50 mr-2"></i> Recuperar utilizador</a>
        <a href="{{route('users.create')}}" class="btn btn-sm btn-primary shadow-sm "><i class="fas fa-plus text-white-50 mr-2"></i> Adicionar utilizador</a>

    </div>

    @endcan


</div>

<!-- Content Row -->
<div class="card shadow mb-4">

    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Lista de utilizadores</h6>
    </div>




    <div class="card-body">


        <div class="table-responsive">

            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th class="text-center">Imagem</th>
                        <th>Utilizador</th>
                        <th>Nome</th>
                        <th>E-mail</th>
                        <th>Perfil</th>
                        <th>Gabinete</th>
                        <th class="text-center">Opções</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach($users as $user)
                    <tr>

                        <!-- USER PHOTO -->
                        <td class="align-middle text-center ">
                            @if ($user->photo)
                            <img src="{{Storage::disk('public')->url('users_photos/').$user->photo}}" class="img_user rounded-circle" alt="Imagem de apresentação">
                            @else
                            <img src="{{asset('img/default_user.png')}}" class="img_user rounded-circle" alt="Imagem de apresentação">
                            @endif
                        </td>

                        <!-- USER ID -->
                        <td class="align-middle">{{ $user->user }}</td>

                        <!-- NOME -->

                        <td class="align-middle">
                            @if ($user->name == null)
                            <span class="text-primary">Aguarda primeiro acesso </span>
                            @else
                            {{ $user->name }}
                            @endif
                        </td>


                        <!-- E-MAIL -->
                        <td class="align-middle">
                            @if ($user->email == null)
                            <span >Sem dados</span>
                            @else
                            {{ $user->email }}
                            @endif
                        </td>

                        <!-- ROLE -->
                        <td class="align-middle">
                            {{$user->roleToStr()}}
                        </td>


                        <!-- Service Initial -->
                        <td class="align-middle">
                            {{$user->serviceToStr()}}
                        </td>



                        <td nowarp class="text-center align-middle">


                            <!-- Função View -->
                            <a class="btn btn-sm btn-outline-primary mb-1" href="{{ route('users.show',$user->user) }}" title="Ver perfil"><i class="fas fa-eye"></i></a>


                            <!-- Função Edit -->
                            @can("update",$user)
                            <a class="btn btn-sm btn-outline-warning  mb-1" href="{{ route('users.edit',$user->user) }}" title="Editar informações"><i class="fas fa-pen"></i></a>
                            @else
                            <span class="btn btn-sm btn-outline-secondary disabled mb-1"><i class="fas fa-pen"></i></span>
                            @endcan



                            <!-- Função delete -->


                            @if ($user->user== Auth::user()->user )<!-- Utilizador não pode eliminar-se  -->

                            <span class="btn btn-sm btn-outline-secondary disabled  mb-1">
                                <i class="fas fa-trash-alt"></i></span>
                                @else

                                @can("delete",$user)

                                <form method="POST" role="form" id="{{ $user->user }}" action="{{route('users.destroy',$user)}}" class="d-inline-block form_user_id" >
                                    @csrf
                                    @method('DELETE')

                                    <button type="submit" class="btn btn-sm btn-outline-danger btn-delete mb-1" title="Eliminar utilizador" data-toggle="modal" data-target="#deleteModal" ><i class="fas fa-trash-alt"></i></button>

                                </form>

                                @else

                                <span class="btn btn-sm btn-outline-secondary disabled mb-1">
                                    <i class="fas fa-trash-alt"></i></span>

                                    @endcan

                                    @endif

                                </td>
                            </tr>
                            @endforeach

                        </tbody>
                    </table>
                </div>
            </div>



        </div>


        @endsection




        @section('scripts')

        <script src="{{asset('/js/script_list_users.js')}}"></script>

        @endsection

resources/views/backoffice/users/show.blade.php
@extends('layout.masterbackoffice')


@section('title', 'Detalhes do utilizador | Utilizadores')

@section('styleLinks')
<link href="{{asset('css/style_add_user.css')}}" rel="stylesheet">
@endsection

@section('content')

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Detalhes do utilizador</h1>
    <div>
        <a href="javascript:history.go(-1)" class="btn btn-sm btn-primary shadow-sm mr-2"><i class="fas fa-chevron-left text-white-50 mr-2"></i>Voltar</a>
        @can("update",$user)
        <a class="btn btn-sm btn-warning shadow-sm" href="{{ route('users.edit',$user->user) }}" title="Editar informações"><i class="fas fa-pen text-white-50 mr-2"></i>Editar Informações</a>
        @else
        <span class="btn btn-sm btn-secondary disabled"><i class="fas fa-pen"></i></span>
        @endcan
    </div>
</div>

<!-- Content Row -->



<div class="card shadow ">

    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Dados do utilizador {{$user->name}}</h6>
    </div>

    <div class="card-body ">


        <div class="row mb-3">

            <!-- Coluna da imgage -->
            <div class="col col-2 col-photo">

                <!-- Verifica se a imagem já existe-->
                @if ($user->photo==null)
                    <img src="{{asset('img/default_user.png')}}" class="img-thumbnail shadow text-center ml-4" alt="Imagem de apresentação" title="Imagem de apresentação" />
                @else
                    <img class="img-thumbnail shadow text-center ml-4" src="{{Storage::disk('public')->url('users_photos/').$user->photo}}">
                @endif

            </div>

            <!-- Coluna dos dados -->
            <div class="col">

                <div class="m-3"><strong>Nome:</strong>
                    @if ($user->name == null)
                    <span class="text-primary">Aguarda primeiro acesso</span>
                    @else
                    {{ $user->name }}
                    @endif
                </div>


                <div class="m-3" ><strong>Email:</strong>
                    @if ($user->email == null)
                    <span>Aguarda primeiro acesso</span>
                    @else
                    {{ $user->email }}
                    @endif
                </div>


                <div class="m-3"><strong>Perfil:</strong>
                    {{$user->roleToStr()}}
                </div>


                <div class="m-3"><strong>Gabinete:</strong>
                    {{$user->serviceToStr()}}
                </div>


                <div class="m-3" ><strong>Utilizador criado em:</strong>
                    {{$user->created_at->format("d/m/Y")}}
                </div>

            </div>

        </div>



        <div class="row mt-3">

            <div class="col mt-3">

                <ul class="nav nav-tabs m-2" id="myTab" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" id="resumo-tab" data-toggle="tab" href="#resumo" role="tab" aria-controls="resumo"
                        aria-selected="true">Resumo</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="history-tab" data-toggle="tab" href="#history" role="tab" aria-controls="history"
                        aria-selected="false">Histórico de atividade</a>
                    </li>

                </ul>

                <div class="tab-content m-2 px-3" id="myTabContent">


                    <div class="tab-pane fade show active p-2" id="resumo" role="tabpanel" aria-labelledby="resumo-tab">
                        <p>Este utilizador é {{$user->roleToStr()}}, e tem permissão para:</p>

                        @if ($user->service_id == null)
                            <ul>
                                <li>Criar novos eventos / divulgaçoes para <strong>qualquer gabinete</strong></li>
                                <li>Editar / modificar quais quer eventos e divulgaçoes já existentes</li>
                                <li>Criar / modificar / eliminar contas de utilizadores</li>
                                <li>Gerir as listas dos públicos alvos</li>
                                <li>Gerir os tipos de divulgações</li>
                                <li>Consultar as estatísticas referentes a todos os gabinetes</li>
                                <li>Criar um backup da base de dados</li>
                                <li>Repor os dados de origem da base de dados</li>

                            </ul>
                        @else
                            <ul>
                                <li>Criar novos eventos / divulgaçoes para o gabinete <strong>{{$user->serviceToStr()}}</strong></li>
                                <li>Editar / modificar quais quer eventos e divulgaçoes já existentes</li>
                                <li>Criar e enviar newsletters em nome do gabinete <strong>{{$user->serviceToStr()}}</strong></li>
                                <li>Consultar as estatísticas referentes ao gabinete <strong>{{$user->serviceToStr()}}</strong></li>
                                <li>Personalizar a sua imagem de apresentação</li>

                            </ul>
                        @endif

                    </div>

                    <div class="tab-pane fade p-2" id="history" role="tabpanel" aria-labelledby="history-tab">


                        <div class="table-responsive " style="overflow:hidden;">
                            <table class="table table-bordered historydetails" nowarp id="dataTable" style="width:100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th class="text-center"># ID</th>
                                        <th>Tipo de publicação</th>
                                        <th>Titulo</th>
                                        <th>Gabinete</th>
                                        <th>Data de criação</th>
                                        <th class="text-center">Opções</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($posts as $post)
                                    <tr>
                                        {{-- ID do post --}}
                                        <td class="align-middle text-center">
                                            {{ $post->id}}
                                        </td>

                                        {{-- Tipo de publicação --}}
                                        <td class="align-middle">
                                            {{ $post->type}} @if ($post->deleted_at!=null)<span class="text-danger">(eliminado)</span>@endif
                                        </td class="align-middle">


                                        {{-- Titulo do post --}}
                                        <td class="align-middle">
                                            {{ $post->title}}
                                        </td>

                                        {{-- Gabinete --}}
                                        <td class="align-middle">
                                            @if ($post->service_id==null)
                                            Não atribuido
                                            @elseif ($post->service_id==1)
                                            GAI&D
                                            @elseif ($post->service_id==2)
                                            GIRE
                                            @else
                                            Internacional
                                            @endif
                                        </td>

                                        {{-- Data de criação --}}
                                        <td class="align-middle">
                                            {{ $post->created_at}}
                                        </td>

                                        {{-- Opções --}}
                                        <td class="text-center align-middle">


                                        @if ($post->deleted_at!=null)
                                            <span class="text-danger">(eliminado)</span>
                                        @else
                                            <a class="btn btn-sm btn-outline-primary mb-1" href="{{ route('posts.show',$post->id) }}" title="Ver publicação"><i class="fas fa-eye"></i></a>
                                            <a class="btn btn-sm btn-outline-warning  mb-1" href="{{ route('posts.edit',$post->id) }}" title="Editar informações"><i class="fas fa-pen"></i></a>
                                        @endif


                                        </td>

                                    </tr>

                                    @endforeach





                                    @foreach($newsletters as $newsletter)
                                    <tr>
                                        {{-- ID do post --}}
                                        <td class="align-middle text-center">
                                            {{$newsletter->id}}
                                        </td>

                                        {{-- Tipo de publicação --}}
                                        <td class="align-middle">
                                            Newsletter @if ($newsletter->deleted_at!=null)<span class="text-danger">(eliminado)</span>@endif
                                        </td>

                                        {{-- Titulo --}}
                                        <td class="align-middle">
                                            {{$newsletter->subject}}
                                        </td>

                                        {{-- Gabinete --}}
                                        <td class="align-middle">
                                            @if ($newsletter->service_id==null)
                                            Não atribuido
                                            @elseif ($newsletter->service_id==1)
                                            GAI&D
                                            @elseif ($newsletter->service_id==2)
                                            GIRE
                                            @else
                                            Internacional
                                            @endif
                                        </td>


                                        {{-- Data de criação --}}
                                        <td class="align-middle">
                                            {{ $newsletter->created_at}}
                                        </td>


                                        {{-- Opções --}}


                                        <td class="align-middle text-center">

                                        @if ($newsletter->deleted_at!=null)
                                            <span class="text-danger">(eliminado)</span>
                                        @else
                                            <a class="btn btn-sm btn-outline-primary mb-1" href="{{ route('newsletters.index') }}" title="Página das Newsletters"><i class="fas fa-external-link-alt"></i></a>
                                        @endif

                                        </td>

                                    </tr>

                                    @endforeach


                                </tbody>
                            </table>
                        </div>



                    </div>


                </div>



            </div>

        </div>

    </div>

</div>






@endsection




@section('scripts')

<script src="{{asset('/js/script_details_users.js')}}"></script>

@endsection