routes/web.php
<?php

use Illuminate\Contracts\Console\Kernel;

// Frontoffice -> Routes

// Index
Route::get('/', 'HomeIndexController@index')->name('index');

//Sobre
Route::get('/sobre', 'PageController@sobre')->name('sobre');

//Contactos
Route::get('/contactos', 'ContactController@contact')->name('contact');
Route::post('/contactos', 'ContactController@contactPost')->name('contactPost');

//Divulgações - Listagem
Route::get('/divulgacoes/{service}', 'PostListController@index')->name('divulgacoes');

//Divulgações - Detalhe
Route::get('/divulgacoes/{service}/divulgacao/{post}', 'PostDetailController@index')->name('divulgacao');

Route::get('/divulgacoes/svgImage/{post}', 'SvgController@getSvg')->name('divulgacoes.svg');
Route::get('/divulgacoes/svgThumb/{post}', 'SvgController@getSvgThumb')->name('divulgacoes.svgThumb');

// Backoffice -> Routes

// Auth
Route::get('/backoffice/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::get('/backoffice/autologin/{number}', 'Auth\LoginController@autoLogin')->name('autologin');
Route::get('/backoffice/logout', 'Auth\LoginController@logout')->name('logout');
Route::post('/backoffice/login', 'Auth\LoginController@postLogin');


Route::group(['prefix' => 'backoffice', 'middleware' => ['auth','PreventBackButton']], function () {

    //Home
    Route::get('/', 'HomeController@index')->name('home');

    //Notes
    Route::resource('/notes', 'NoteController')->only([
        'store', 'update', 'destroy'
    ]);

    //Statistics
    Route::resource('/statistics', 'StatisticsController');

    //Users
    Route::get('/users//restore/{user}', 'UserController@restore')->name('users.restore');
    Route::get('/users/restore', 'UserController@show_trashed')->name('users.trashed');
    Route::resource('/users', 'UserController');

    //Services: EDIT info
    Route::resource('/services', 'ServicesController');

    //FAQs
    Route::get('/faqs', 'FaqsController@show')->name('faqs');

    //Options
    Route::get('/options/reset', 'OptionsController@show_reset')->name('resetpage');


    //Reset à base de dados : migrate:refresh
    Route::get('/options/resetdata', function () {
        $exitCode = Artisan::call('migrate:refresh');
        return redirect()->route('options', Auth::user())->with('success', 'Valores de origem repostos com sucesso');
    })->name('resetdatabase');

/*     //backup database. php artisan backup:mysql-dump
    Route::get('/options/backup/makebackup', function () {
        $exitCode = Artisan::call('backup:mysql-dump');
        return redirect()->route('options', Auth::user())->with('success', 'Cópia de segurança da base de dados efectuada com sucesso');
    })->name('makebackup'); */





    Route::get('/options/backup', 'OptionsController@show_backup')->name('backupdatabase');
    Route::get('/options/{user}', 'OptionsController@index')->name('options');


    //Drafts
    Route::resource('/drafts', 'DraftController');

    // Newsletter
    Route::get('/newsletters', 'NewsletterController@index')->name('newsletters.index');
    Route::get('/newsletters/create', 'NewsletterController@create')->name('newsletters.create');
    Route::post('/newsletters/preview', 'NewsletterController@preview')->name('newsletters.preview');
    Route::post('/newsletters/store', 'NewsletterController@store')->name('newsletters.store');
    Route::delete('/newsletters/{newsletter}', 'NewsletterController@destroy')->name('newsletters.destroy');


    //Drafts
    Route::resource('/drafts', 'DraftController')->only(['index', 'show', 'edit', 'destroy']);

    //Events
    Route::resource('/events', 'EventController')->only([
        'index', 'show', 'edit', 'destroy'
    ]);

    //Posts
    Route::get('/posts/create/{tipo}','PostController@create')->name('posts.create');
    Route::resource('/posts', 'PostController')->except(['create']);

    //Tasks
    Route::resource('/tasks', 'TaskController')->only([
        'index', 'store', 'update', 'destroy'
    ]);

    //SubTasks
    Route::resource('/subtasks', 'SubTaskController')->only([
        'index', 'store', 'update', 'destroy'
    ]);
    Route::put('/updatesubtaskstatusdone/{id}',[
      'as' => 'subtasks.updateStatusDone',
      'uses' => 'SubTaskController@updateStatusDone'
    ]);
    Route::put('/updatesubtaskstatustodo/{id}',[
      'as' => 'subtasks.updateStatusTodo',
      'uses' => 'SubTaskController@updateStatusTodo'
    ]);

    //EventTypes
    Route::resource('/eventtypes', 'EventTypeController')->only([
        'index', 'store', 'update', 'destroy'
    ]);

    //TargetAudience
    Route::resource('/targetaudiences', 'TargetAudienceController')->only([
        'index', 'store', 'update', 'destroy'
    ]);
    Route::get('/getEmails', 'TargetAudienceController@getEmails');

    Route::put('/notifications/markAsRead/{id}', 'NotificationController@markAsRead');
});

app/Http/Controllers/EventTypeController.php
<?php

namespace App\Http\Controllers;

use App\EventType;
use App\Service;
use Auth;
use Illuminate\Http\Request;
use App\Http\Requests\StoreEventTypesRequest;
use App\Http\Requests\UpdateEventTypesRequest;

class EventTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      if(Auth::user()->isAdmin()){
        $services=Service::all();
        $eventTypes=EventType::all();
        return view('backoffice.eventTypes.list', compact('eventTypes', 'services'));
      }else{
        $service=Service::findOrFail(Auth::user()->service_id);
        $eventTypes=$service->eventtypes;
        return view('backoffice.eventTypes.list', compact('eventTypes'));
      }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $EventType=new EventType;
        return view('backoffice.eventTypes.add', compact("EventType"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreEventTypesRequest $request)
    {
      $fields=$request->validated();
      $eventType=new EventType();
      $eventType->fill($fields);
      $eventType->save();
      return $eventType->load('service');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\EventType  $eventType
     * @return \Illuminate\Http\Response
     */
    public function show(EventType $eventType)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\EventType  $eventType
     * @return \Illuminate\Http\Response
     */
    public function edit(EventType $eventType)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\EventType  $eventType
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateEventTypesRequest $request, EventType $eventType)
    {
      $fields=$request->validated();
      $eventType=EventType::findOrFail($request->id);
      $eventType->fill($fields);
      $eventType->save();
      return $eventType->load('service');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\EventType  $eventType
     * @return \Illuminate\Http\Response
     */
    public function destroy(EventType $eventType, $id)
    {
      $eventType=EventType::findOrFail($id);
      $eventType->delete();
      return 'deleted';
    }
}

resources/views/backoffice/eventTypes/list.blade.php
@extends('layout.masterbackoffice')

@section('title', 'Tipos de Publicação')

@section('styleLinks')
<link href="{{asset('css/dataTables.bootstrap4.min.css')}}" rel="stylesheet">
<link rel="stylesheet" href="{{asset('vendor/iconpicker/dist/css/fontawesome-iconpicker.min.css')}}">
@endsection

@section('content')

  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Tipos de Publicação</h1>
    <button id="btn_add_eventType" class="btn btn-sm btn-primary shadow-sm" data-toggle="modal" data-target="#ModalEventTypesAdd"><i class="fas fa-plus text-white-50 mr-2"></i>Adicionar Tipo de Publicação</button>
  </div>

  <!-- Content Row -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Lista de Tipos de Publicação</h6>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="tableEventyTypes" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Designação</th>
              <th>Ícone</th>
              @if(Auth::user()->isAdmin())<th>Gabinete</th>@endif
                <th>Opções</th>
              </tr>
            </thead>

            <tbody>
              @foreach($eventTypes as $eventType)
                <tr id="{{$eventType->id}}">
                  <td>{{$eventType->name}}</td>
                  <td><i class="{{$eventType->icon}}"></i> <span style="font-size:12px;">({{$eventType->icon}})</span></td>
                  @if(Auth::user()->isAdmin())<td>{{$eventType->service->initial}}</td>@endif
                    <td class="text-center align-middle">
                      <button class="btn btn-sm btn-outline-warning mb-1" data-toggle="modal" data-target="#ModalEventTypesEdit" data-id='{{$eventType->id}}' @if(Auth::user()->isAdmin()) data-service-id='{{$eventType->service_id}}' @endif data-name='{{$eventType->name}}' data-icon='{{$eventType->icon}}' title="Editar Tipo de Publicação"><i class="fas fa-pen"></i></button>
                      <button class="btn btn-sm btn-outline-danger btn-delete mb-1" data-toggle="modal" data-target="#ModalEventTypesDelete" data-id='{{$eventType->id}}' @if(Auth::user()->isAdmin()) data-service-id='{{$eventType->service_id}}' @endif data-name='{{$eventType->name}}' data-icon='{{$eventType->icon}}' title="Eliminar Tipo de Publicação"><i class="fas fa-trash-alt"></i></button>
                    </td>
                  </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <!-- Modal Add EventType-->
      <div class="modal fade" id="ModalEventTypesAdd" role="dialog">
        <div class="modal-dialog modal-md" role="document">
          <div class="modal-content">
            <form class="" id="form_add" action="{{route('eventtypes.store')}}" method="post">
              @csrf
              <div class="modal-header">
                <h5 class="modal-title">Adicionar Tipo de Publicação</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                @include('backoffice.eventTypes.partials.add-edit', ['action' => 'add'])
              </div>
              <div class="modal-footer">
                <button type="submit"class="btn btn-sm btn-primary">Guardar</button>
                <button type="cancel" class="btn btn-sm btn-secondary" data-dismiss="modal">Cancelar</button>
              </div>
            </form>
          </div>
        </div>
      </div>

      <!-- Modal Edit EventType-->
      <div class="modal fade" id="ModalEventTypesEdit" role="dialog">
        <div class="modal-dialog modal-md" role="document">
          <div class="modal-content">
            <form class="" id="form_edit" action="" method="post">
              @method('PUT')
              @csrf
              <div class="modal-header">
                <h5 class="modal-title">Editar Tipo de Publicação</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                @include('backoffice.eventTypes.partials.add-edit', ['action' => 'edit'])
                <input type="hidden" id="eventtype_edit_id" name="id" value="">
              </div>
              <div class="modal-footer">
                <button type="submit" class="btn btn-sm btn-primary">Guardar</button>
                <button type="cancel" class="btn btn-sm btn-secondary" data-dismiss="modal">Cancelar</button>
              </div>
            </form>
          </div>
        </div>
      </div>

      <!-- Modal Delete EventType-->
      <div class="modal fade" id="ModalEventTypesDelete" role="dialog">
        <div class="modal-dialog modal-md" role="document">
          <div class="modal-content">
            <form class="" id="form_delete" action="" method="post">
              @method('DELETE')
              @csrf
              <div class="modal-header">
                <h5 class="modal-title">Eliminar Tipo de Publicação</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p>Tem a certeza que pretende eliminar o Tipo de Publicação "<b><span id="designacaoTipo"></span></b>"?</p>
                <input type="hidden" id="eventtype_delete_id" name="id" value="">
              </div>
              <div class="modal-footer">
                <button type="submit" class="btn btn-sm btn-danger">Confirmar</button>
                <button type="cancel" class="btn btn-sm btn-secondary" data-dismiss="modal">Cancelar</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    @endsection



    @section("scripts")

      <script src="{{asset('vendor/iconpicker/dist/js/fontawesome-iconpicker.js')}}"></script>

      <script>
      $(document).ready(function() {

        $('.demo').iconpicker();
        $('#error_alert_add').hide();
        $('#error_alert_edit').hide();

        var table=$('#tableEventyTypes').DataTable( {
          "columnDefs": [
            { targets:-1, 'width': '70px', 'orderable':false, 'className': 'text-center align-middle'},
          ],
          "language": {
            "lengthMenu":  "Mostrar _MENU_ registos por página",
            "search":      "Procurar:",
            "zeroRecords": "Sem registos",
            "paginate": {
              "first":      "Primeiro",
              "last":       "Ultimo",
              "next":       "Próximo",
              "previous":   "Anterior"
            },

            "info": "A mostrar página _PAGE_ de _PAGES_",
            "infoEmpty": "Sem registos disponiveis",
            "infoFiltered": "(filtrado de um total de _MAX_ registos)"
          },
          @if(Auth::user()->isAdmin()) "order": [[2, 'asc'],[0, 'asc']]
          @else "order": [0, 'asc'] @endif

        } );


        $('#form_add').submit(function(){
          var data=$(this).serialize();
          data+=('&icon='+$('#eventtype_add_icon').attr('class'));
          $.ajax({
            url: "{{route('eventtypes.store')}}",
            data: data,
            method: 'POST',
            success: function(data){
              table.row.add([data['name'], "<i class='"+data['icon']+"'></i> <span style='font-size:12px;'>("+data['icon']+")</span>", @if(Auth::user()->isAdmin()) data['service']['initial'], @endif "<button class='btn btn-sm btn-outline-warning mb-1' data-toggle='modal' data-target='#ModalEventTypesEdit' data-id='"+data['id']+"' @if(Auth::user()->isAdmin()) data-service-id='"+data['service_id']+"' @endif data-name='"+data['name']+"' data-icon='"+data['icon']+"' title='Editar Tipo de Publicação'><i class='fas fa-pen'></i></button> <button class='btn btn-sm btn-outline-danger btn-delete mb-1' data-toggle='modal' data-target='#ModalEventTypesDelete' data-id='"+data['id']+"' data-name='"+data['name']+"' data-icon='"+data['icon']+"' title='Eliminar Tipo de Publicação'><i class='fas fa-trash-alt'></i></button>"]).node().id = data['id'];
              table.draw();
              $("#ModalEventTypesAdd").modal('hide');
            },
            error: function(data){
              var errors=data['responseJSON']['errors']
              var string="";
              $.each(errors, function( index, value ) {
                string+=value+"<br>";
              });;
              $("#error_alert_add").find('h6').html(string);
              $("#error_alert_add").fadeTo(4000, 500).slideUp();
            }
          });
          return false;
        });

        $('#form_edit').submit(function(){
          var data=$(this).serialize();
          var idEventType=$("#eventtype_edit_id").val();
          data+=('&icon='+$('#eventtype_edit_icon').attr('class'));
          $.ajax({
            url: "/backoffice/eventtypes/"+idEventType,
            data: data,
            method: 'POST',
            success: function(data){
              console.log(data);
              table.row($('#'+data['id'])).data([data['name'], "<i class='"+data['icon']+"'></i> <span style='font-size:12px;'>("+data['icon']+")</span>", @if(Auth::user()->isAdmin()) data['service']['initial'], @endif "<button class='btn btn-sm btn-outline-warning mb-1' data-toggle='modal' data-target='#ModalEventTypesEdit' data-id='"+data['id']+"' @if(Auth::user()->isAdmin()) data-service-id='"+data['service_id']+"' @endif data-name='"+data['name']+"' data-icon='"+data['icon']+"' title='Editar Tipo de Publicação'><i class='fas fa-pen'></i></button> <button class='btn btn-sm btn-outline-danger btn-delete mb-1' data-toggle='modal' data-target='#ModalEventTypesDelete' data-id='"+data['id']+"' data-name='"+data['name']+"' data-icon='"+data['icon']+"' title='Eliminar Tipo de Publicação'><i class='fas fa-trash-alt'></i></button>"]).draw();
              $("#ModalEventTypesEdit").modal('hide');
            },
            error: function(data){
              var errors=data['responseJSON']['errors']
              var string="";
              $.each(errors, function( index, value ) {
                string+=value+"<br>";
              });;
              $("#error_alert_edit").find('h6').html(string);
              $("#error_alert_edit").fadeTo(4000, 500).slideUp();
            }
          });
          return false;
        });

        $('#form_delete').submit(function(){
          var data=$(this).serialize();
          var idEventType=$("#eventtype_delete_id").val();
          $.ajax({
            url: "/backoffice/eventtypes/"+idEventType,
            data: data,
            method: 'POST',
            success: function(data){
              table.row($('#'+idEventType)).remove().draw();
              $("#ModalEventTypesDelete").modal('hide');
            },
            error: function(){
              alert('error!');
            }
          });
          return false;
        });

        $('#ModalEventTypesEdit').on('show.bs.modal', function (event) {
          var button = $(event.relatedTarget) // Button that triggered the modal
          var modal = $(this)
          modal.find('#eventtype_edit_name').val(button.data('name'));
          modal.find('#eventtype_edit_icon').attr('class', button.data('icon'));
          modal.find('#eventtype_edit_id').val(button.data('id'));
          @if(Auth::user()->isAdmin())
            modal.find('#eventtype_edit_service').val(button.data('service-id'));
          @endif
        });

        $('#ModalEventTypesDelete').on('show.bs.modal', function (event) {
          var button = $(event.relatedTarget) // Button that triggered the modal
          var modal = $(this)
          modal.find('#designacaoTipo').html(button.data('name'));
          modal.find('#eventtype_delete_id').val(button.data('id'));
        })

        $("#btn_add_eventType").click(function(){
          var modal = $('#ModalEventTypesAdd');
          modal.find('#eventtype_add_name').val('');
        });

      });

      </script>
    @endsection