routes/web.php
<?php

use Illuminate\Contracts\Console\Kernel;

// Frontoffice -> Routes

// Index
Route::get('/', 'HomeIndexController@index')->name('index');

//Sobre
Route::get('/sobre', 'PageController@sobre')->name('sobre');

//Contactos
Route::get('/contactos', 'ContactController@contact')->name('contact');
Route::post('/contactos', 'ContactController@contactPost')->name('contactPost');

//Divulgações - Listagem
Route::get('/divulgacoes/{service}', 'PostListController@index')->name('divulgacoes');

//Divulgações - Detalhe
Route::get('/divulgacoes/{service}/divulgacao/{post}', 'PostDetailController@index')->name('divulgacao');

Route::get('/divulgacoes/svgImage/{post}', 'SvgController@getSvg')->name('divulgacoes.svg');
Route::get('/divulgacoes/svgThumb/{post}', 'SvgController@getSvgThumb')->name('divulgacoes.svgThumb');

// Backoffice -> Routes

// Auth
Route::get('/backoffice/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::get('/backoffice/autologin/{number}', 'Auth\LoginController@autoLogin')->name('autologin');
Route::get('/backoffice/logout', 'Auth\LoginController@logout')->name('logout');
Route::post('/backoffice/login', 'Auth\LoginController@postLogin');


Route::group(['prefix' => 'backoffice', 'middleware' => ['auth','PreventBackButton']], function () {

    //Home
    Route::get('/', 'HomeController@index')->name('home');

    //Notes
    Route::resource('/notes', 'NoteController')->only([
        'store', 'update', 'destroy'
    ]);

    //Statistics
    Route::resource('/statistics', 'StatisticsController');

    //Users
    Route::get('/users//restore/{user}', 'UserController@restore')->name('users.restore');
    Route::get('/users/restore', 'UserController@show_trashed')->name('users.trashed');
    Route::resource('/users', 'UserController');

    //Services: EDIT info
    Route::resource('/services', 'ServicesController');

    //FAQs
    Route::get('/faqs', 'FaqsController@show')->name('faqs');

    //Options
    Route::get('/options/reset', 'OptionsController@show_reset')->name('resetpage');


    //Reset à base de dados : migrate:refresh
    Route::get('/options/resetdata', function () {
        $exitCode = Artisan::call('migrate:refresh');
        return redirect()->route('options', Auth::user())->with('success', 'Valores de origem repostos com sucesso');
    })->name('resetdatabase');

/*     //backup database. php artisan backup:mysql-dump
    Route::get('/options/backup/makebackup', function () {
        $exitCode = Artisan::call('backup:mysql-dump');
        return redirect()->route('options', Auth::user())->with('success', 'Cópia de segurança da base de dados efectuada com sucesso');
    })->name('makebackup'); */





    Route::get('/options/backup', 'OptionsController@show_backup')->name('backupdatabase');
    Route::get('/options/{user}', 'OptionsController@index')->name('options');


    //Drafts
    Route::resource('/drafts', 'DraftController');

    // Newsletter
    Route::get('/newsletters', 'NewsletterController@index')->name('newsletters.index');
    Route::get('/newsletters/create', 'NewsletterController@create')->name('newsletters.create');
    Route::post('/newsletters/preview', 'NewsletterController@preview')->name('newsletters.preview');
    Route::post('/newsletters/store', 'NewsletterController@store')->name('newsletters.store');
    Route::delete('/newsletters/{newsletter}', 'NewsletterController@destroy')->name('newsletters.destroy');


    //Drafts
    Route::resource('/drafts', 'DraftController')->only(['index', 'show', 'edit', 'destroy']);

    //Events
    Route::resource('/events', 'EventController')->only([
        'index', 'show', 'edit', 'destroy'
    ]);

    //Posts
    Route::get('/posts/create/{tipo}','PostController@create')->name('posts.create');
    Route::resource('/posts', 'PostController')->except(['create']);

    //Tasks
    Route::resource('/tasks', 'TaskController')->only([
        'index', 'store', 'update', 'destroy'
    ]);

    //SubTasks
    Route::resource('/subtasks', 'SubTaskController')->only([
        'index', 'store', 'update', 'destroy'
    ]);
    Route::put('/updatesubtaskstatusdone/{id}',[
      'as' => 'subtasks.updateStatusDone',
      'uses' => 'SubTaskController@updateStatusDone'
    ]);
    Route::put('/updatesubtaskstatustodo/{id}',[
      'as' => 'subtasks.updateStatusTodo',
      'uses' => 'SubTaskController@updateStatusTodo'
    ]);

    //EventTypes
    Route::resource('/eventtypes', 'EventTypeController')->only([
        'index', 'store', 'update', 'destroy'
    ]);

    //TargetAudience
    Route::resource('/targetaudiences', 'TargetAudienceController')->only([
        'index', 'store', 'update', 'destroy'
    ]);
    Route::get('/getEmails', 'TargetAudienceController@getEmails');

    Route::put('/notifications/markAsRead/{id}', 'NotificationController@markAsRead');
});

app/Http/Controllers/OptionsController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;



class OptionsController extends Controller
{

    public function index($loggeduser)
    {

        $services = DB::table('services')->get();

        // POSTS do utilizaror
        $posts = DB::table('posts')
        ->select('*')
        ->where('user', $loggeduser)
        ->get();


        // NEWSLETTERS do utilizador
        $newsletters = DB::table('newsletters')
        ->select('*')
        ->where('user', $loggeduser)
        ->get();

        return view('backoffice.options.options', compact('services','posts','newsletters'));

    }



    public function show_reset()
    {
        if(Auth::User()->role!='Admin'){
            abort (401);
        }

        return view('backoffice.options.reset');

    }


    public function show_backup()
    {

        if(Auth::User()->role!='Admin'){
            abort (401);
        }
        return view('backoffice.options.backup');

    }




    public function resetdatabase()
    {
        //Schema::disableForeignKeyConstraints();


        //Artisan::call('migrate', array('--path' => 'app/migrations', '--force' => true));


        return redirect()->route('options',Auth::user())->with('success', 'Valores de origem repostos com sucesso');

    }






    public function backupdatabase()
    {

        return redirect()->route('options')->with('success', 'Backup criado com sucesso ');

    }




}

resources/views/backoffice/options/backup.blade.php
@extends('layout.masterbackoffice')




@section('title', 'Backup Base de dados | Definições')


@section('styleLinks')
<link href="{{asset('css/style_add_user.css')}}" rel="stylesheet">
@endsection

@section('content')


<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Backup da base de dados</h1>
    <a href="javascript:history.go(-1)" class="btn btn-sm btn-primary shadow-sm mr-2"><i class="fas fa-chevron-left text-white-50 mr-2"></i>Página anterior</a>
</div>


 <div class="card shadow mb-4">

    <div class="card-body">
        <div class="row mb-3">

{{--     <a href="{{ route('makebackup') }}">sssssssssdssss</a> --}}

    </div>
  </div>
 </div>

@endsection



@section('scripts')


@endsection

resources/views/backoffice/options/options.blade.php
@extends('layout.masterbackoffice')




@section('title', 'Definições')


@section('styleLinks')
<link href="{{asset('css/style_options.css')}}" rel="stylesheet">
@endsection

@section('content')


<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Definições</h1>

</div>


 <div class="card shadow mb-4">

    <div class="card-body">
        <div class="row mb-3">

                {{-- Fotografia --}}
                <div class="col col-2 col-photo ">
                    @if (Auth::user()->photo==null)
                    <img src="{{asset('img/default_user.png')}}" id="userphoto" class="img-thumbnail rounded-circle shadow ml-4" alt="Imagem de apresentação" title="Imagem de apresentação" />
                    @else
                    <img class="img-thumbnail shadow text-center ml-4" src="{{Storage::disk('public')->url('users_photos/').Auth::user()->photo}}">
                    @endif
                </div>


                {{-- Dados do utilizador --}}
                <div class="col">
                    <div class="m-3"><strong>Nome:</strong>
                        @if (Auth::user()->name == null)
                        <span class="text-primary">Aguarda primeiro acesso</span>
                        @else
                        {{ Auth::user()->name }}
                        @endif
                    </div>

                    <div class="m-3" ><strong>Email:</strong>
                        @if (Auth::user()->email == null)
                        <span>Aguarda primeiro acesso</span>
                        @else
                        {{ Auth::user()->email }}
                        @endif
                    </div>


                    <div class="m-3"><strong>Perfil:</strong>
                        {{Auth::user()->roleToStr()}}
                    </div>


                    <div class="m-3"><strong>Gabinete:</strong>
                        {{Auth::user()->serviceToStr()}}
                    </div>


                    <div class="m-3" ><strong>Utilizador criado em:</strong>
                        {{Auth::user()->created_at->format("d/m/Y")}}
                    </div>
                </div>

        </div>

        {{-- resumo e actividade --}}

        <div class="row ">

            <div class="col mt-3">
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                    <li class="nav-item">
                      <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Opções</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Resumo</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Histórico de atividade</a>
                    </li>
                  </ul>
                  <div class="tab-content p-2" id="myTabContent">

                    {{-- Opções --}}
                    <div class="tab-pane fade show p-3 active" id="home" role="tabpanel" aria-labelledby="home-tab">


                        <p><a class="btn btn-sm btn-outline-warning mr-2" href="{{ route('users.edit', Auth::user()->user) }}" title="Editar informações de perfil"><i class="fas fa-user "></i></a> Editar informações do perfil</p>


                    @if (Auth::user()->role=="Admin" )

                    <br>
                    @foreach($services as $service)
                        <p><a class="btn btn-sm btn-outline-success mb-1 mr-2" href="{{ route('services.edit',$service->id) }}" title="Editar informações do gabinete"><i class="fas fa-cog"></i></a> Editar informações do gabinete <strong>{{$service->initial}}</strong><br></p>
                    @endforeach

                    {{-- <p class="mt-5"><a class="btn btn-sm btn-outline-danger mb-1 mr-2" href="{{ route('backupdatabase') }}" title="Fazer um backup da base de dados"><i class="fas fa-database"></i></a> Cópia de segurança da base de dados<br></p> --}}
                    <br><p><a class="btn btn-sm btn-outline-danger mb-1 mr-2" href="{{ route('resetpage') }}" title="Repor valores de origem"><i class="fas fa-recycle"></i></a> Repor valores de origem<br></p>

                    @else
                    <a class="btn btn-sm btn-outline-success mb-1 mr-2" href="{{ route('services.edit',Auth::User()->service_id) }}" title="Editar informações do gabinete"><i class="fas fa-cog"></i></a> Editar informações do gabinete <strong>{{Auth::user()->serviceToStr()}}</strong><br>
                    @endif


                    </div>

                    {{-- Resumo --}}
                    <div class="tab-pane fade p-2" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                        <p>{{Auth::user()->name}} utiliza esta plataforma com o perfil de {{Auth::user()->roleToStr()}}, e tem permissão para:</p>

                        @if (Auth::user()->service_id == null)
                            <ul>
                                <li>Criar novos eventos / divulgaçoes para <strong>qualquer gabinete</strong></li>
                                <li>Editar / modificar quais quer eventos e divulgaçoes já existentes</li>
                                <li>Criar / modificar / eliminar contas de utilizadores</li>
                                <li>Gerir as listas dos públicos alvos</li>
                                <li>Gerir os tipos de divulgações</li>
                                <li>Consultar as estatísticas referentes a todos os gabinetes</li>
                                <li>Criar um backup da base de dados</li>
                                <li>Repor os dados de origem da base de dados</li>
                            </ul>

                        @else
                            <ul>
                                <li>Criar novos eventos / divulgaçoes para o gabinete <strong>{{Auth::user()->serviceToStr()}}</strong></strong></li>
                                <li>Editar / modificar quais quer eventos e divulgaçoes já existentes</li>
                                <li>Criar e enviar newsletters em nome do gabinete <strong>{{Auth::user()->serviceToStr()}}</strong></li>
                                <li>Gerir as listas dos públicos alvos</li>
                                <li>Gerir os tipos de divulgações</li>
                                <li>Consultar as estatísticas referentes ao gabinete <strong>{{Auth::user()->serviceToStr()}}</strong></li>
                                <li>Personalizar a sua imagem de apresentação</strong></li>
                            </ul>

                        @endif

                        <a class="btn btn-sm btn-outline-primary rounded-circle mr-2" href="{{route('faqs')}}" title="Editar informações do gabinete"><i class="fas fa-question"></i></a> Para mais informações poderá consultar os tópicos de ajuda<br>
                    </div>

                    {{-- Histórico de actividade --}}
                    <div class="tab-pane fade p-2" id="contact" role="tabpanel" aria-labelledby="contact-tab">
                        <div class="table-responsive " style="overflow:hidden;">
                            <table class="table table-bordered" id="dataTable" style="width:100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th class="text-center"># ID</th>
                                        <th>Tipo de publicação</th>
                                        <th>Titulo</th>
                                        <th>Gabinete</th>
                                        <th>Data de criação</th>
                                        <th class="text-center">Opções</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($posts as $post)
                                    <tr>
                                        {{-- ID do post --}}
                                        <td class="align-middle text-center">
                                            {{ $post->id}}
                                        </td>

                                        {{-- Tipo de publicação --}}
                                        <td class="align-middle">
                                            {{ $post->type}} @if ($post->deleted_at!=null)<span class="text-danger">(eliminado)</span>@endif
                                        </td class="align-middle">


                                        {{-- Titulo do post --}}
                                        <td class="align-middle">
                                            {{ $post->title}}
                                        </td>

                                        {{-- Gabinete --}}
                                        <td class="align-middle">
                                            @if ($post->service_id==null)
                                            Não atribuido
                                            @elseif ($post->service_id==1)
                                            GAI&D
                                            @elseif ($post->service_id==2)
                                            GIRE
                                            @else
                                            Internacional
                                            @endif
                                        </td>

                                        {{-- Data de criação --}}
                                        <td class="align-middle">
                                            {{ $post->created_at}}
                                        </td>

                                        {{-- Opções --}}
                                        <td class="text-center align-middle">
                                            @if ($post->deleted_at!=null)
                                                <span class="text-danger">(eliminado)</span>
                                            @else
                                                <a class="btn btn-sm btn-outline-primary mb-1" href="{{ route('posts.show',$post->id) }}" title="Ver publicação"><i class="fas fa-eye"></i></a>
                                                <a class="btn btn-sm btn-outline-warning mb-1" href="{{ route('posts.edit',$post->id) }}" title="Editar informações"><i class="fas fa-pen"></i></a>
                                            @endif

                                        </td>


                                    </tr>

                                    @endforeach



                                    @foreach($newsletters as $newsletter)
                                    <tr>
                                        {{-- ID do post --}}
                                        <td class="align-middle text-center">
                                            {{$newsletter->id}}
                                        </td>

                                        {{-- Tipo de publicação --}}
                                        <td class="align-middle">
                                            Newsletter @if ($newsletter->deleted_at!=null)<span class="text-danger">(eliminado)</span>@endif
                                        </td>

                                        {{-- Titulo --}}
                                        <td class="align-middle">
                                            {{$newsletter->subject}}
                                        </td>

                                        {{-- Gabinete --}}
                                        <td class="align-middle">
                                            @if ($newsletter->service_id==null)
                                            Não atribuido
                                            @elseif ($newsletter->service_id==1)
                                            GAI&D
                                            @elseif ($newsletter->service_id==2)
                                            GIRE
                                            @else
                                            Internacional
                                            @endif
                                        </td>


                                        {{-- Data de criação --}}
                                        <td class="align-middle">
                                            {{ $newsletter->created_at}}
                                        </td>


                                        {{-- Opções --}}
                                        <td class="align-middle text-center">

                                        @if ($newsletter->deleted_at!=null)
                                            <span class="text-danger">(eliminado)</span>
                                        @else
                                            <a class="btn btn-sm btn-outline-primary mb-1" href="{{ route('newsletters.index') }}" title="Página das Newsletters"><i class="fas fa-external-link-alt"></i></a>
                                        @endif

                                        </td>



                                    </tr>

                                    @endforeach

                                </tbody>
                            </table>
                        </div>
                    </div>




                  </div>
            </div>

        </div>

    </div>
  </div>

@endsection


@section('scripts')

<script src="{{asset('/js/script_details_users.js')}}"></script>

@endsection

resources/views/backoffice/options/reset.blade.php
@extends('layout.masterbackoffice')




@section('title', 'Repor valores de origem | Definições')


@section('styleLinks')
<link href="{{asset('css/style_add_user.css')}}" rel="stylesheet">
@endsection

@section('content')


<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Repor valores de origem</h1>
    <a href="javascript:history.go(-1)" class="btn btn-sm btn-primary shadow-sm mr-2"><i class="fas fa-chevron-left text-white-50 mr-2"></i>Página anterior</a>
</div>


 <div class="card shadow">

    <div class="card-body ">

        <div class="alert alert-danger mb-4" role="alert">
           <i class="fas fa-exclamation-triangle mr-3"></i><strong>Atenção:</strong> Esta ação é irreversivel. Ao repor os valores de origem irá perder os todos dados registados atualmente.
          </div>


         {{--  Repor cópia de segurança --}}
          <div class="row">

                 {{-- Repor dados de origem --}}
            <div class="col">
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                      <h6 class="m-0 font-weight-bold text-primary">Repor dados de origem</h6>
                    </div>
                    <div class="card-body">
                        <p>Antes de utilizar esta função, é recomendado fazer um backup da base de dados, pois todos os dados serão perdidos.</p>
                        <p style="line-height:28px">
                        - Publicações / eventos <br>
                        - Registo de envio das Newsletters <br>
                        - Rascunhos <br>
                        - Tipos de divulgações personalizados <br>
                        - Publicações / eventos <br>
                        - Listas de emails de publico alvo<br>
                        - Utilizadores registados (exepto administrador predefinido) <br>
                        - Lista de tarefas / notas pessoais <br>
                        - Dados estatísticos<br>
                        </p>


                    <div class="text-right">
                    <button type="button" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#exampleModal">
                        <i class="fas fa-recycle mr-2"></i>Repor dados de origem
                    </button>
                    </div>

                </div>
                </div>
            </div>


{{--              <div class="col col-md-6">
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                      <h6 class="m-0 font-weight-bold text-primary">Repor cópia de segurança</h6>
                    </div>
                    <div class="card-body">

                        <p>Esta opção permite repor os dados através de um ficheiro de cópia de segurança criado anteriormente.</p>

                        <p>- Selecione o ficheiro da cópia de segurança</p>

                        <div class="input-group" >
                            <div class="custom-file">
                              <input type="file" class="custom-file-input" id="inputGroupFile02">
                              <label class="custom-file-label" for="inputGroupFile02" aria-describedby="inputGroupFileAddon02">Escolher ficheiro</label>
                            </div>
                          </div>

                          <div class="text-right">
                          <a class="mt-4 btn btn-sm btn-primary text-white">Repor cópia de segurança</a>
                        </div>

                    </div>
                  </div>
            </div> --}}


        </div>


  </div>
 </div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Repor valores de origem</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Tem a certeza que quer repor os valores de origem?</p>
          <i class="fas fa-exclamation-triangle mr-2"></i><strong>Aviso: Esta ação é irreversivel. Todos os dados guardados atualmente serão perdidos!</strong>
        </div>
        <div class="modal-footer">
          <a class="btn btn-sm btn-danger" href="{{route('resetdatabase')}}">Sim! Repor valores de origem</a>
          <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Cancelar</button>
        </div>
      </div>
    </div>
  </div>


@endsection

{{-- Repor através de backup |  Repor através de backup --}}

resources/views/backoffice/options/serviceedit.blade.php
@extends('layout.masterbackoffice')

@section('title', 'Editar informações de gabinete | Definições')

@section('styleLinks')
<link href="{{asset('css/style_options.css')}}" rel="stylesheet">
@endsection


@section('content')

    <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Informações do gabinete {{$service->initial}}</h1>
        <a href="javascript:history.go(-1)" class="btn btn-sm btn-primary shadow-sm "><i class="fas fa-chevron-left text-white-50 mr-2"></i>Voltar</a>
    </div>

<!-- Basic Card Example -->
<div class="card shadow main-card">
    <div class="card-body ">

        <div class="row">

            <div class="col pr-3">
                <form method="POST" action="{{route('services.update',$service)}}" class="form-group" id="form_user" enctype="multipart/form-data">
                    @csrf
                    @method("PUT")

                    <div class="row">

                        <div class="col col-md-6">
                            <label for="name"><span class="text-danger"><small>&#10033;</small></span> Nome do gabinete</label>
                            <input type="text" class="form-control" name="name" id="name" value="{{old('name',$service->name)}}" maxlength="120" title="Nome do gabinete" placeholder="Insira o nome do gabinete">
                        </div>
                        <div class="col col-md-6">
                            <label for="initial"><span class="text-danger"><small>&#10033;</small></span> Iniciais</label>
                            <input type="text" class="form-control" style="width:180px;text-transform: uppercase;" name="initial" id="initial" value="{{old('name',$service->initial)}}" maxlength="15" title="Iniciais do gabinete">
                        </div>

                    </div>


                        <br>

                        <label for="description"><span class="text-danger"><small>&#10033;</small></span> Descrição do gabinete</label>
                        <input type="text" class="form-control" name="description" id="description" value="{{old('description',$service->description)}}" maxlength="150" title="Descrição do gabinete" placeholder="Insira a descrição do gabinete">

                        <br>

                        <div class="row">

                            <div class="col">
                                <label for="email"><span class="text-danger"><small>&#10033;</small></span> E-mail</label>
                                <input type="email" class="form-control" name="email" id="email" value="{{old('email',$service->email)}}"  maxlength="250" title="exemplto@servidor.pt" placeholder="Insira o email do gabinete" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$">
                            </div>
                            <div class="col">
                                <label for="phone"><span class="text-danger"></span> Telefone</label>
                                <input type="text" class="form-control" name="phone" id="phone" value="{{old('name',$service->phone)}}" maxlength="15" title="Telefone do gabinete" placeholder="Insira o telefone do gabinete">
                            </div>

                        </div>

                        <br><br>
                        <small><span class="campo_obrigatorio text-danger">&#10033;</span> Campos de preenchimento campo obrigatório</small><br>

                <div class="form-group text-right">
                    <br><br>
                <a href="javascript:history.go(-1)" class="btn btn-sm btn-secondary shadow-sm mr-2"><i class="fas fa-chevron-left text-white-50 mr-2"></i>Cancelar</a>
                <button type="submit" class="btn btn-sm btn-success mr-1" name="ok" id="buttonSubmit"><i class="far fa-save mr-2"></i>Guardar dados</button>
                <a href="#" class="btn btn-sm btn-info shadow-sm mr-2" id="buttonPreview"><i class="fas fa-search text-white-50 mr-2"></i> Prever</a>
                </form>

                </div>

            </div>



            <div id="preview" class="col col-md-5 text-center ml-4 p-4 card bg-light preview">
                <h4>Aparência atual</h4>
                <small>Clique no botão "Prever" para atualizar</small><br>
                <div class="card text-center shadow-sm mx-auto" style="width: 75%">

                    <div class="card-body ">
                        <h5 class="card-title" style="text-transform: uppercase" id="mockupInitial">{{ $service->initial }}</h5>
                        <small class="text-muted" id="mockupName">{{ $service->name }}</small>
                        <p class="card-text mt-3" id="mockupDescription">{{ $service->description }}</p>
                    </div>
                    <div class="card-footer border-light">
                        <a href="#" id="mockupEmail">{{ $service->email }}</a>
                        <br>
                        <div id="mockupPhone">Telefone: {{ $service->phone }}</div>
                    </div>
                </div>
            </div>

        </div>

    </div>
</div>


@endsection


@section('scripts')

<script src="{{asset('/js/script_edit_service.js')}}"></script>

@endsection